spring:
  application:
    name: smart-trip-api
  ai:
    openai:
      api-key: ${openai.api.key}
      chat:
        options:
          model: gpt-4.1
          temperature: 1.2
          max-tokens: 8192
