spring:
  application:
    name: smart-trip-api
  ai:
    openai:
      api-key: ${openai.api.key}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
          max-tokens: 1000
